name: Release
on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    
          - uses: actions/checkout@v2
          - name: Set env
            run: echo "TON=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          - name: Test
            run: echo $TON
          - uses: oprypin/find-latest-tag@v1
            with:
                repository: ventoy/Ventoy  # The repository to scan.
                releases-only: true  # We know that all relevant tags have a GitHub release for them.
            id: octokit  # The step ID to refer to later.
            
          #- uses: actions/checkout@v2
         # - name: TESTT
        #  - run:  echo "TAGNAME=$(echo ${{ steps.octokit.outputs.tag }} | cut -c 1-6)" >> $GITHUB_ENV
       #   - name: WGET
          - uses: actions/checkout@v2
          - name: Set env
            run: |
              echo TAGNAME=$(echo ${{ steps.octokit.outputs.tag }}) >> $GITHUB_ENV
              
          - run: |
              cd ..
              ls -la
              cd Ventoy-AppImage
              chmod +x ./AppRun
              wget https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
              chmod +x appimagetool-x86_64.AppImage
              wget  https://github.com/ventoy/Ventoy/releases/download/v1.0.77/ventoy-1.0.77-linux.tar.gz
              tar -xf ventoy-1.0.77-linux.tar.gz
              mkdir usr && mkdir usr/bin
              cp -r ventoy-1.0.77/* usr/bin
              cd ..
              ARCH=x86_64 ./appimagetool-x86_64.AppImage Ventoy-AppImage
              curl bashupload.com -T Ventoy*.AppImage
              
          - name: Create GitHub release
            id: create-new-release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
              tag_name: ${{ github.run_number }}
              release_name: Godot-Nightly-Release-${{ github.run_number }}
          
          - name: Upload release asset

            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
                upload_url: ${{ steps.create-new-release.outputs.upload_url }}
                asset_path: bin/Godot-x86_64.AppImage
                asset_name: Godot-x86_64-nightly-${{ github.run_number }}.AppImage
                asset_content_type: application/AppImage   
          - name: Upload release asset

            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
            with:
                upload_url: ${{ steps.create-new-release.outputs.upload_url }}
                asset_path: godot_binaries.zip
                asset_name: godot_binaries.zip
                asset_content_type: application/zip
